"""
Generate lookup tables for SNES GPT transcendental functions.
Outputs tables.asm with ExpTable and InvSqrtTable as ca65 .word data.
"""
import math
import os

def main():
    lines = []
    lines.append("; ==========================================================================")
    lines.append("; Lookup Tables for SNES GPT — Generated by gen_tables.py")
    lines.append("; ==========================================================================")
    lines.append("")
    lines.append(".p816")
    lines.append('.include "snes.inc"')
    lines.append("")
    lines.append(".segment \"RODATA\"")
    lines.append("")

    # --- ExpTable: 256 entries covering [-4.0, +4.0) ---
    lines.append("; ExpTable: exp(x) for x in [-4.0, +4.0), 256 entries")
    lines.append("; Index i -> x = -4.0 + i * (8.0/256)")
    lines.append("; Values are Q8.8 unsigned (exp is always positive)")
    lines.append(".export ExpTable")
    lines.append("ExpTable:")
    for i in range(256):
        x = -4.0 + i * 8.0 / 256
        val = math.exp(x) * 256.0
        q = int(round(val))
        q = max(0, min(32767, q))  # clamp to unsigned Q8.8 range
        lines.append(f"    .word ${q:04X}    ; [{i:3d}] exp({x:+.3f}) = {math.exp(x):.4f}")
    lines.append("")

    # --- InvSqrtTable: 256 entries covering [0.0039, 4.0) ---
    # Index i -> x = (i+1) * (4.0/256) in Q8.8
    # We map input Q8.8 values: index = (x >> 2) & 0xFF for x in [0, 4.0)
    # More precisely: index = x_q8 >> 2, clamped to [0,255]
    lines.append("; InvSqrtTable: 1/sqrt(x) for x in (0, 4.0), 256 entries")
    lines.append("; Index i -> x = (i+1) / 64.0  (Q8.8 value >> 2 gives index)")
    lines.append("; Values are Q8.8")
    lines.append(".export InvSqrtTable")
    lines.append("InvSqrtTable:")
    for i in range(256):
        x = (i + 1) / 64.0  # maps i=0 -> x=1/64=0.0156, i=255 -> x=4.0
        val = 1.0 / math.sqrt(x)
        q = int(round(val * 256.0))
        q = max(0, min(32767, q))
        lines.append(f"    .word ${q:04X}    ; [{i:3d}] 1/sqrt({x:.4f}) = {val:.4f}")
    lines.append("")

    import sys
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    outpath = os.path.join(outdir, "tables.asm")
    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {outpath} with {256 + 256} entries")


if __name__ == "__main__":
    main()
